spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  messages:
    basename: i18n/response/response,i18n/view/view

comment:
  avatar: /images/default-avatar.jpg

